services:
  web:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    restart: "always"

  discord_bot:
    build: .
    command: python -m discord_bot.main
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - web
    restart: "always"

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
    restart: "always"

  selenium_worker:
    build: .
    #command: python -m selenium_bot.aws_login
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - selenium-chrome
      - web
    restart: "always"
