services:
  web:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  discord_bot:
    build: .
    command: python discord_bot/main.py
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - web
