-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 21:13:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema anima
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema anima
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `anima` DEFAULT CHARACTER SET utf8 ;
USE `anima` ;

-- -----------------------------------------------------
-- Table `anima`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_discord_id` CHAR(20) NULL,
  `usuario_nome` VARCHAR(120) NOT NULL,
  `usuario_email` VARCHAR(60) NOT NULL,
  `usuario_ra` CHAR(12) NULL,
  `usuario_discord_name` VARCHAR(60) NULL,
  `usuario_validado_code` CHAR(6) NULL,
  `usuario_validado` TINYINT NOT NULL DEFAULT 0,
  `usuario_validado_data` TIMESTAMP NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`uc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`uc` (
  `uc_id` INT NOT NULL AUTO_INCREMENT,
  `uc_nome` VARCHAR(100) NOT NULL,
  `uc_role_id` CHAR(20) NULL,
  `uc_ano` CHAR(4) NULL,
  `uc_semestre` CHAR(1) NULL,
  `uc_dia_semana` SMALLINT NULL,
  PRIMARY KEY (`uc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`usuario_kahoot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`usuario_kahoot` (
  `usuario_kahoot_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `usuario_kahoot_nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`usuario_kahoot_id`),
  INDEX `fk_usuario_kahoot_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_kahoot_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `anima`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`ponto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`ponto` (
  `ponto_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `uc_id` INT NOT NULL,
  `tipo_ponto` ENUM('Presença', 'Participação', 'Kahoot', 'Curso') NOT NULL,
  `dt_ponto` TIMESTAMP NOT NULL,
  `num_ponto` FLOAT NOT NULL,
  `comentario_ponto` TEXT NOT NULL,
  PRIMARY KEY (`ponto_id`),
  INDEX `fk_ponto_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_ponto_uc1_idx` (`uc_id` ASC) VISIBLE,
  CONSTRAINT `fk_ponto_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `anima`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ponto_uc1`
    FOREIGN KEY (`uc_id`)
    REFERENCES `anima`.`uc` (`uc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`curso` (
  `curso_id` INT NOT NULL AUTO_INCREMENT,
  `curso_parceira` ENUM('Red Hat', 'Google', 'AWS', 'Cisco', 'Microsoft', 'Oracle') NOT NULL,
  `curso_nome` VARCHAR(120) NOT NULL,
  `curso_dt_inicio` TIMESTAMP NOT NULL,
  `curso_dt_fim` TIMESTAMP NOT NULL,
  `curso_agente` VARCHAR(60) NOT NULL,
  `curso_role` CHAR(22) NULL,
  `curso_param` VARCHAR(100) NULL,
  `curso_sinonimos` TEXT NULL,
  `curso_carga_horaria` INT NULL,
  `curso_url_inscricao` VARCHAR(255) NULL,
  PRIMARY KEY (`curso_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`usuario_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`usuario_curso` (
  `usuario_curso_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_redhat_id` VARCHAR(60) NULL,
  `usuario_redhat_email` VARCHAR(100) NULL,
  `usuario_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `usuario_curso_dt_solicitacao` TIMESTAMP NOT NULL DEFAULT now(),
  `usuario_curso_dt_inscricao` TIMESTAMP NULL,
  `usuario_curso_situacao` ENUM('Pendente', 'Concluído') NOT NULL DEFAULT 'Pendente',
  PRIMARY KEY (`usuario_curso_id`),
  INDEX `fk_usuario_curso_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_usuario_curso_curso1_idx` (`curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_curso_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `anima`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_curso_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `anima`.`curso` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
