-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 21:13:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema anima
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema anima
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `anima` DEFAULT CHARACTER SET utf8 ;
USE `anima` ;

-- -----------------------------------------------------
-- Table `anima`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_discord_id` CHAR(20) NULL,
  `usuario_nome` VARCHAR(120) NOT NULL,
  `usuario_email` VARCHAR(60) NOT NULL,
  `usuario_email_pessoal` VARCHAR(150) NULL,
  `usuario_ra` VARCHAR(20) NULL,
  `ies_sigla` VARCHAR(15) NULL,
  `curso_sigla` VARCHAR(10) NULL,
  `usuario_discord_name` VARCHAR(60) NULL,
  `usuario_validado_code` CHAR(6) NULL,
  `usuario_validado` TINYINT NOT NULL DEFAULT 0,
  `usuario_validado_data` TIMESTAMP NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`uc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`uc` (
  `uc_id` INT NOT NULL AUTO_INCREMENT,
  `uc_nome` VARCHAR(100) NOT NULL,
  `uc_role_id` CHAR(20) NULL,
  `uc_ano` CHAR(4) NULL,
  `uc_semestre` CHAR(1) NULL,
  `uc_dia_semana` SMALLINT NULL,
  PRIMARY KEY (`uc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`usuario_kahoot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`usuario_kahoot` (
  `usuario_kahoot_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `usuario_kahoot_nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`usuario_kahoot_id`),
  INDEX `fk_usuario_kahoot_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_kahoot_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `anima`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`ponto`
-- -----------------------------------------------------
-- Table `anima`.`pontuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`pontuacao` (
  `pontuacao_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `uc_id` INT NOT NULL,
  `pontuacao` DECIMAL(5,2) NULL,
  `data_pontuacao` TIMESTAMP NOT NULL DEFAULT NOW(),
  `pontuacao_descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`pontuacao_id`),
  INDEX `fk_pontuacao_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_pontuacao_uc_idx` (`uc_id` ASC) VISIBLE,
  CONSTRAINT `fk_pontuacao_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `anima`.`usuario` (`usuario_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_pontuacao_uc`
    FOREIGN KEY (`uc_id`)
    REFERENCES `anima`.`anima_uc` (`uc_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`curso` (
  `curso_id` INT NOT NULL AUTO_INCREMENT,
  `curso_parceira` ENUM('Red Hat', 'Google', 'AWS', 'Cisco', 'Microsoft', 'Oracle') NOT NULL,
  `curso_nome` VARCHAR(120) NOT NULL,
  `curso_dt_inicio` TIMESTAMP NOT NULL,
  `curso_dt_fim` TIMESTAMP NOT NULL,
  `curso_agente` VARCHAR(60) NOT NULL,
  `curso_role` CHAR(22) NULL,
  `curso_param` VARCHAR(100) NULL,
  `curso_sinonimos` TEXT NULL,
  `curso_carga_horaria` INT NULL,
  `curso_url_inscricao` VARCHAR(255) NULL,
  PRIMARY KEY (`curso_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`usuario_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`usuario_curso` (
  `usuario_curso_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_redhat_id` VARCHAR(60) NULL,
  `usuario_redhat_email` VARCHAR(100) NULL,
  `usuario_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `usuario_curso_dt_solicitacao` TIMESTAMP NOT NULL DEFAULT now(),
  `usuario_curso_dt_inscricao` TIMESTAMP NULL,
  `usuario_curso_situacao` ENUM('Pendente', 'Inscrito', 'Concluído', 'Validado', 'Creditado') NOT NULL DEFAULT 'Pendente',
  `usuario_curso_url_comprovante` VARCHAR(255) NULL,
  `usuario_curso_dt_conferencia` TIMESTAMP NULL,
  PRIMARY KEY (`usuario_curso_id`),
  INDEX `fk_usuario_curso_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_usuario_curso_curso1_idx` (`curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_curso_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `anima`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_curso_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `anima`.`curso` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
-- -----------------------------------------------------
-- Table `anima`.`anima_usuario_discord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`anima_usuario_discord` (
  `discord_user_id` VARCHAR(25) NOT NULL,
  `discord_username` VARCHAR(100) NULL,
  `discord_global_name` VARCHAR(100) NULL,
  `discord_avatar_url` VARCHAR(255) NULL,
  `usuario_id` INT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`discord_user_id`),
  INDEX `fk_anima_usuario_discord_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_anima_usuario_discord_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `anima`.`usuario` (`usuario_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`anima_quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`anima_quiz` (
  `quiz_id` INT NOT NULL AUTO_INCREMENT,
  `quiz_titulo` VARCHAR(150) NOT NULL,
  `quiz_descricao` TEXT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`quiz_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`anima_quiz_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`anima_quiz_tema` (
  `quiz_id` INT NOT NULL,
  `temas_interesse_id` INT NOT NULL,
  PRIMARY KEY (`quiz_id`, `temas_interesse_id`),
  INDEX `fk_anima_quiz_tema_tema_idx` (`temas_interesse_id` ASC),
  CONSTRAINT `fk_anima_quiz_tema_quiz`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `anima`.`anima_quiz` (`quiz_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_anima_quiz_tema_tema`
    FOREIGN KEY (`temas_interesse_id`)
    REFERENCES `anima`.`anima_temas_interesse` (`temas_interesse_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`anima_quiz_pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`anima_quiz_pergunta` (
  `pergunta_id` INT NOT NULL AUTO_INCREMENT,
  `quiz_id` INT NOT NULL,
  `pergunta_ordem` INT NOT NULL DEFAULT 1,
  `pergunta_enunciado` TEXT NOT NULL,
  `pergunta_imagem_url` VARCHAR(500) NULL,
  `tempo_limite_segundos` INT NOT NULL DEFAULT 20,
  `pontos_base` INT NOT NULL DEFAULT 1000,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`pergunta_id`),
  INDEX `fk_anima_quiz_pergunta_quiz_idx` (`quiz_id` ASC),
  CONSTRAINT `fk_anima_quiz_pergunta_quiz`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `anima`.`anima_quiz` (`quiz_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`anima_quiz_alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`anima_quiz_alternativa` (
  `alternativa_id` INT NOT NULL AUTO_INCREMENT,
  `pergunta_id` INT NOT NULL,
  `alternativa_letra` CHAR(1) NOT NULL,
  `alternativa_texto` VARCHAR(100) NOT NULL,
  `is_correta` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`alternativa_id`),
  INDEX `fk_anima_quiz_alternativa_pergunta_idx` (`pergunta_id` ASC),
  CONSTRAINT `fk_anima_quiz_alternativa_pergunta`
    FOREIGN KEY (`pergunta_id`)
    REFERENCES `anima`.`anima_quiz_pergunta` (`pergunta_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`anima_quiz_aplicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`anima_quiz_aplicacao` (
  `aplicacao_id` INT NOT NULL AUTO_INCREMENT,
  `quiz_id` INT NOT NULL,
  `uc_id` INT NOT NULL,
  `data_hora_prevista` DATETIME NOT NULL,
  `status` ENUM('Agendado', 'Em Andamento', 'Concluido', 'Cancelado') NOT NULL DEFAULT 'Agendado',
  `discord_channel_id` VARCHAR(25) NULL,
  `data_hora_inicio` DATETIME NULL,
  `data_hora_fim` DATETIME NULL,
  `pontos_1_lugar` DECIMAL(5,2) NOT NULL DEFAULT 1.00,
  `pontos_2_lugar` DECIMAL(5,2) NOT NULL DEFAULT 1.00,
  `pontos_3_lugar` DECIMAL(5,2) NOT NULL DEFAULT 1.00,
  `pontos_4_lugar` DECIMAL(5,2) NOT NULL DEFAULT 0.80,
  `pontos_5_lugar` DECIMAL(5,2) NOT NULL DEFAULT 0.80,
  `pontos_6_lugar` DECIMAL(5,2) NOT NULL DEFAULT 0.80,
  `pontos_7_lugar` DECIMAL(5,2) NOT NULL DEFAULT 0.50,
  `pontos_8_lugar` DECIMAL(5,2) NOT NULL DEFAULT 0.50,
  `pontos_9_lugar` DECIMAL(5,2) NOT NULL DEFAULT 0.50,
  `pontos_10_lugar` DECIMAL(5,2) NOT NULL DEFAULT 0.50,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`aplicacao_id`),
  INDEX `fk_anima_quiz_aplicacao_quiz_idx` (`quiz_id` ASC),
  INDEX `fk_anima_quiz_aplicacao_uc_idx` (`uc_id` ASC),
  CONSTRAINT `fk_anima_quiz_aplicacao_quiz`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `anima`.`anima_quiz` (`quiz_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_anima_quiz_aplicacao_uc`
    FOREIGN KEY (`uc_id`)
    REFERENCES `anima`.`anima_uc` (`uc_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`anima_quiz_resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`anima_quiz_resposta` (
  `resposta_id` INT NOT NULL AUTO_INCREMENT,
  `aplicacao_id` INT NOT NULL,
  `pergunta_id` INT NOT NULL,
  `alternativa_id` INT NOT NULL,
  `discord_user_id` VARCHAR(25) NOT NULL,
  `data_hora_resposta` DATETIME(3) NOT NULL,
  `tempo_gasto_ms` INT NOT NULL,
  `is_correta` TINYINT(1) NOT NULL DEFAULT 0,
  `pontos_ganhos` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`resposta_id`),
  UNIQUE KEY `uk_aplicacao_pergunta_user` (`aplicacao_id`, `pergunta_id`, `discord_user_id`),
  INDEX `fk_anima_quiz_resposta_app_idx` (`aplicacao_id` ASC),
  INDEX `fk_anima_quiz_resposta_pergunta_idx` (`pergunta_id` ASC),
  INDEX `fk_anima_quiz_resposta_alt_idx` (`alternativa_id` ASC),
  INDEX `fk_anima_quiz_resposta_user_idx` (`discord_user_id` ASC),
  CONSTRAINT `fk_anima_quiz_resposta_app`
    FOREIGN KEY (`aplicacao_id`)
    REFERENCES `anima`.`anima_quiz_aplicacao` (`aplicacao_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_anima_quiz_resposta_pergunta`
    FOREIGN KEY (`pergunta_id`)
    REFERENCES `anima`.`anima_quiz_pergunta` (`pergunta_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_anima_quiz_resposta_alt`
    FOREIGN KEY (`alternativa_id`)
    REFERENCES `anima`.`anima_quiz_alternativa` (`alternativa_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_anima_quiz_resposta_user`
    FOREIGN KEY (`discord_user_id`)
    REFERENCES `anima`.`anima_usuario_discord` (`discord_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anima`.`anima_quiz_participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anima`.`anima_quiz_participante` (
  `aplicacao_id` INT NOT NULL,
  `discord_user_id` VARCHAR(25) NOT NULL,
  `pontuacao_total` INT NOT NULL DEFAULT 0,
  `acertos` INT NOT NULL DEFAULT 0,
  `tempo_total_ms` INT NOT NULL DEFAULT 0,
  `posicao_final` INT NULL,
  `pontos_atribuidos` DECIMAL(5,2) NULL,
  PRIMARY KEY (`aplicacao_id`, `discord_user_id`),
  INDEX `fk_anima_quiz_part_user_idx` (`discord_user_id` ASC),
  CONSTRAINT `fk_anima_quiz_part_app`
    FOREIGN KEY (`aplicacao_id`)
    REFERENCES `anima`.`anima_quiz_aplicacao` (`aplicacao_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_anima_quiz_part_user`
    FOREIGN KEY (`discord_user_id`)
    REFERENCES `anima`.`anima_usuario_discord` (`discord_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
